### ISSUE TITLE
Huge bundle size

### ISSUE THREAD

**Issue by LouisRitchie** [rehypejs/rehype-highlight#9]
1mb default bundle size, no way to change that through this library. What's up with that? I'm looking into it.

**Comment by LouisRitchie** [comment]
Both highlight and lowlight libraries mention that you shouldn't `require('lowlight')` because it's 1mb, but you should go through the process of requiring only those languages that you need. Wondering if we can do that here.

**Comment by wooorm** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by LouisRitchie** [comment]
lmao bye noob
